version: "3.9"

x-base: &base
  env_file:
    - ./app/.env
  restart: always
  networks:
    - docker_net


services:
  app:
    <<: *base
    build: ./
    ports:
      - "0.0.0.0:8001:8001"
    volumes:
      - ./app:/app
    command: sh -c "npm i && npm run start:dev"
  postgres:
    <<: *base
    image: postgres:13.2
    volumes:
      - finances-app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5431:5432"
networks:
  docker_net:
    name: dev_docker_net
volumes:
  finances-app-postgres:
